language: node_js
node_js:
  - stable

#before_install:
#  - git config --global user.email "travis@travis-ci.org"
#  - git config --global user.name "Travis CI"
script:
  - npm run build
after_success:
  - SOURCE_BRANCH="master"
  - TARGET_BRANCH="gh-pages"
  - SOURCE_DIR=${PWD##*/}
  - TARGET_DIR=$TARGET_BRANCH
  - REPO=`git config remote.origin.url`
  - PROJECT=`echo $REPO | sed 's/.*github.com//' | sed -e 's/^[//]*//' | sed -e 's/^[:]*//'`

  # Clone my repo one folder up for gh-pages version
  - cd ..
  - git clone $REPO $TARGET_DIR --branch $TARGET_BRANCH --single-branch --depth 1
  - cd $TARGET_DIR

  # set remote on gh-pages version

  # clean (remove unchecked in files) gh-page version
  - git clean -f -d

  # fetch and Checkout gh-page branch
  - git pull origin

  # remove existing files
  - rm -rf ./*

  # copy files from dist to gh-page branch
  - cp -R ../$SOURCE_DIR/dist/* ../$TARGET_DIR

  - cat ./index.html >> ./404.html

  # setup user
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"

  # set github access token
  - git config github.token $github_token

  # Add files
  - git add .

  # commit changes
  - git commit -m "Travis Deploy, travis build $TRAVIS_BUILD_NUMBER"

  # push
  - git push https://$GITHUB_API_KEY@github.com/$PROJECT $TARGET_BRANCH

env:
  global:
    secure: "pXGHuXEJaqOdGbZV6kyqtKrlnKWI1+R4ttNWe1eq9MKcn5gWdoUi67yUNnEuyDPY7Ia1lkwdenD8ti6uBB70oOMev74IiG0Ep5iSEW9JJezLtfXX9GB/2o/z8IyOcuHCAW6RuTVETGEYmtxPDJbg3euP1qKfEHApgqjZhC1rY2YnH1c2jWtenOMsyL5HNwlVtOIe7boGlDTfD1vVaizy3GNiCz3SjDzG8osYEok1GnTV5HGbpK3NHdx63r+jLHn+iLUZEkkugqvpVF4N6Lb5IOIXF5FIAe6BjmZjZSnUkRke+/fRI5YFZ21ktikr3eZEaQTqljaiZdDdWKgljkYVZR6WxhAybwY+jUNMx9hGrfk5zSHVaFAUan4oBRXuBw3ZNgy+jxriQzgFIE2t5jgu3Tnl/p6fVRl4EAbEJ/MbmsfP2J5047a3H8DjA8kfqlzp39t/94ZMNzqx+wZ4iUOtr88jjWh0Q2lpeyPErgMBPpSzBbPGqDzVoKd0XxhqY+mMoA9rjN8IF8f8I0SpQbgFXs5y9/C9/jBcQO6ImsVjAGoxMPXuOxChIhbbH+0vk4pfScw9rDgAM1j5L2ZvjawQbE8dmOVi9XFlQ2OIZyIjYSanSp3Tn6PM0iBivMoz/Eiqi8JjANVmammFEDtTqgrqjZlYjBNQQ9Hs9pLOwYOKhZ8="

